---
title: "LCA - Final Figures"
format: 
  html:
    code-fold: true
    theme: lux
    embed-resources: true
execute:
  warning: false
  message: false
---

```{r}
library(tidyverse)
library(here)
library(gt)
```

```{r}
containers <- read_csv(here("data/all_containers.csv")) %>%
  mutate(impact_type = case_when(
    impact_type == "Ecotoxicity (recommended)" ~ "Ecotoxicity",
    impact_type == "Ozone Depletion Air" ~ "Ozone Depletion",
    impact_type == "Human Health Particulate Air" ~ "Particulate Air",
    TRUE ~ impact_type
  ))

normalized_total_impact <- read_csv(here("data/normalized_total_impact.csv")) %>%
  mutate(impact_type = case_when(
    impact_type == "Ecotoxicity (recommended)" ~ "Ecotoxicity",
    impact_type == "Ozone Depletion Air" ~ "Ozone Depletion",
    impact_type == "Human Health Particulate Air" ~ "Particulate Air",
    TRUE ~ impact_type
  ))
```

# Sensitivity Analysis of Scenarios

```{r}
containers %>% 
  filter(container == "aluminium",
         process == "total_impact") %>% 
  group_by(scenario, impact_type) %>%
  ggplot(aes(x = scenario, y = value, fill = scenario)) +
  geom_bar(stat="identity", position = "dodge") +
  labs(y = "Total Impact",
       x = "Scenario",
       title = "Aluminium",
       subtitle = "Sensitivity Analysis by Impact Category") +
  theme_bw() +
  facet_wrap(~impact_type, scales = "free_y") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.3))) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
containers %>% 
  filter(container == "PET",
         process == "total_impact") %>% 
  group_by(scenario, impact_type) %>%
  ggplot(aes(x = scenario, y = value, fill = scenario)) +
  geom_bar(stat="identity", position = "dodge") +
  labs(y = "Total Impact",
       x = "Scenario",
       title = "PET",
       subtitle = "Sensitivity Analysis by Impact Category") +
  theme_bw() +
  facet_wrap(~impact_type, scales = "free_y") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.3))) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
containers %>% 
  filter(container == "glass",
         process == "total_impact") %>% 
  group_by(scenario, impact_type) %>%
  ggplot(aes(x = scenario, y = value, fill = scenario)) +
  geom_bar(stat="identity", position = "dodge") +
  labs(y = "Total Impact",
       x = "Scenario",
       title = "Glass",
       subtitle = "Sensitivity Analysis by Impact Category") +
  theme_bw() +
  facet_wrap(~impact_type, scales = "free_y") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.3))) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
baseline_p <- ggplot(normalized_total_impact, aes(x = impact_type, y = normalized_value, fill = container)) +
  geom_col(position = "dodge") +  
  scale_x_discrete(guide = guide_axis(angle = 45)) +
  scale_y_continuous(
    limits = c(0, 3.0),  
    breaks = seq(0, 3.0, by = 0.3),  
    expand = expansion(mult = c(0, 0)),
    position = "left"
  ) +
   scale_fill_discrete(labels = c(
    "aluminium_normalized" = "Aluminium",
    "PET_normalized" = "PET",
    "glass_normalized" = "Glass"
  ))+
  labs(title = "Environmental Impact by Container",
       x = "Impact Category",
       y = "Normalized Value",
       fill = "Container") +
  theme_minimal() +
  theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(), 
      panel.grid.minor.y = element_blank(),
      panel.background = element_rect(fill = "white", color = NA),
      axis.line = element_line(color = "grey"),
      plot.margin = margin(5, 5, 5, 5),
      plot.title = element_text(margin = margin(b = 5)),
      legend.margin = margin(0, 0, 0, 10),
      aspect.ratio = 0.4,
      axis.title.y = element_text(margin = margin(r = 5)),
      axis.title.x = element_text(margin = margin(t = 5))
  )

baseline_p
```

## Contribution Analysis

```{r}
containers %>% 
  filter(container == "aluminium") %>% 
  group_by(life_cycle, impact_type) %>%
  # Reorder life_cycle factor levels
  mutate(life_cycle = factor(life_cycle, 
                             levels = c("production", "transportation", "end-of-life", "total_impact"))) %>%
  ggplot(aes(x = life_cycle, y = value, fill = life_cycle)) +
  geom_bar(stat="identity", position = "dodge") +
  labs(y = "Total Impact",
       x = "Life Cycle Stage",
       title = "Aluminium",
       subtitle = "Contribution Analysis by Impact Category") +
  theme_bw() +
  facet_wrap(~impact_type, scales = "free_y") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.3))) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
containers %>% 
  filter(container == "PET") %>% 
  group_by(life_cycle, impact_type) %>%
  # Reorder life_cycle factor levels
  mutate(life_cycle = factor(life_cycle, 
                             levels = c("production", "transportation", "end-of-life", "total_impact"))) %>%
  ggplot(aes(x = life_cycle, y = value, fill = life_cycle)) +
  geom_bar(stat="identity", position = "dodge") +
  labs(y = "Total Impact",
       x = "Life Cycle Stage",
       title = "PET",
       subtitle = "Contribution Analysis by Impact Category") +
  theme_bw() +
  facet_wrap(~impact_type, scales = "free_y") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.3))) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
containers %>% 
  filter(container == "glass") %>% 
  group_by(life_cycle, impact_type) %>%
  # Reorder life_cycle factor levels
  mutate(life_cycle = factor(life_cycle, 
                             levels = c("production", "transportation", "end-of-life", "total_impact"))) %>%
  ggplot(aes(x = life_cycle, y = value, fill = life_cycle)) +
  geom_bar(stat="identity", position = "dodge") +
  labs(y = "Total Impact",
       x = "Life Cycle Stage",
       title = "Glass",
       subtitle = "Contribution Analysis by Impact Category") +
  theme_bw() +
  facet_wrap(~impact_type, scales = "free_y") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.3))) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

